version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.2
    - 1.440.4
    - 1.441.0
    - 1.445.0
    - 1.446.0
    - 1.448.0
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.458.0
    - 1.459.0
    - 1.460.0
    - 1.463.0
    - 1.464.0
    - 1.467.0
    - 1.471.0
    - 1.476.0
    - 1.477.0
    - 1.479.0
    - 1.483.0
    - 1.487.0
    - 1.489.0
    - 1.490.0
    - 1.493.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.506.0
    - 1.509.0
    - 1.512.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.529.0
    - 1.531.0
    - 1.534.0
    - 1.539.0
    - 1.542.0
    - 1.559.0
    - 1.563.0
    - 1.564.0
    - 1.567.0
    - 1.570.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: bl
    versions:
    - 4.0.4
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
